# Generated by Django 5.0 on 2024-02-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlog",
            name="product",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
